[build]
publish = "dist" # Specify the directory where your built files are located
command = "npm run build" # Specify the build command
environment = { NODE_VERSION = "18.17.1", NPM_VERSION = "9.6.7" }

[dev]
command = "npm run dev" # Specify the development server command
